# Generated by Django 4.0.4 on 2022-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='mascota'),
        ),
        migrations.AlterField(
            model_name='formularioadopcion',
            name='tipo_vivienda',
            field=models.IntegerField(choices=[[0, 'Casa'], [1, 'Departamento']]),
        ),
    ]
