# Generated by Django 4.0.4 on 2022-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mascota_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='cantidad_mascotas',
            field=models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, 'Más de 2']]),
        ),
    ]
