# Generated by Django 4.0.4 on 2022-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_formularioadopcion_cantidad_mascotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nombre_especie',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='raza',
            name='nombre_raza',
            field=models.CharField(max_length=250),
        ),
    ]
