# Generated by Django 4.0.4 on 2022-05-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_especie_nombre_especie_alter_raza_nombre_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_mascota',
            field=models.CharField(max_length=250),
        ),
    ]
