# Generated by Django 4.0.4 on 2022-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mascota_edad_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.CharField(max_length=250),
        ),
    ]
