# Generated by Django 4.0.4 on 2022-05-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacion',
            new_name='Contacto',
        ),
    ]
