# Generated by Django 4.0.4 on 2022-06-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_contacion_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MascotaAdopcion',
        ),
    ]
