# Generated by Django 4.0.4 on 2022-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mascotadesaparecida_remove_mascotaperdida_mascota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotadesaparecida',
            name='numero_contacto',
            field=models.IntegerField(default=20),
        ),
    ]
