# Generated by Django 4.0.4 on 2022-06-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_mascotadesaparecida_numero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotadesaparecida',
            name='numero_contacto',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
