# Generated by Django 4.0.4 on 2022-06-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_mascotadesaparecida_numero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True),
        ),
    ]
