# Generated by Django 4.0.4 on 2022-06-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_formularioadopcion_fecha_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioadopcion',
            name='estado_solicitud',
        ),
    ]
