# Generated by Django 4.0.4 on 2022-06-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_formularioadopcion_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioadopcion',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.mascota'),
        ),
    ]
