# Generated by Django 4.0.4 on 2022-06-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_formularioadopcion_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioadopcion',
            name='mascota',
        ),
    ]
