# Generated by Django 4.0.4 on 2022-06-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_formularioadopcion_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
