# Generated by Django 4.0.4 on 2022-06-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_contacto_avisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.CharField(choices=[['Consulta', 'Consulta'], ['Reclamo', 'Reclamo'], ['Sugerencia', 'Sugerencia'], ['Agradecimientos', 'Agradecimientos']], max_length=20),
        ),
    ]
