# Generated by Django 4.0.4 on 2022-06-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioadopcion',
            name='estado_solicitud',
            field=models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aprobada', 'Aprobada'], ['Rechazada', 'Rechazada']], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='mascotadesaparecida',
            name='tipo_publicacion',
            field=models.CharField(choices=[['Mascota Perdida', 'Mascota Perdida'], ['Mascota Encontrada', 'Mascota Encontrada']], max_length=50),
        ),
    ]
