# Generated by Django 4.0.4 on 2022-06-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_formularioadopcion_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='estado_solicitud',
            field=models.IntegerField(choices=[[0, 'Pendiente'], [1, 'Aprobada'], [2, 'Rechazada']], default=0),
        ),
    ]
