# Generated by Django 4.0.4 on 2022-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_formularioadopcion_cantidad_mascotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='edad',
            field=models.IntegerField(max_length=3),
        ),
    ]
