# Generated by Django 4.0.4 on 2022-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_formularioadopcion_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
