# Generated by Django 4.0.4 on 2022-06-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_formularioadopcion_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='cantidad_mascotas',
            field=models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6']]),
        ),
    ]
